openai-response-api:
	@python openai-response-api.py

install-dependencies:
	@pip install -r requirements.txt

crewai-agent:
	@streamlit run crewai-agent.py

openai-agent-sdk:
	@python openai-agent-sdk.py

openai-agent-sdk-streamlit:
	@streamlit run openai-agent-sdk-streamlit.py

.PHONY: openai-response-api install-dependencies crewai-agent openai-agent-sdk openai-agent-sdk-streamlit
