stages:
  process_data:
    cmd: python src/read_data.py
    deps:
    - src/read_data.py
    - data/data.csv
    outs:
    - data/processed/processed_data.csv
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    - data/processed/processed_data.csv
    - params.yaml
    params:
    - prepare.test_size
    - prepare.random_state
    outs:
    - data/prepared/train.csv
    - data/prepared/test.csv
  train:
    cmd: python src/train_data.py
    deps:
    - src/train_data.py
    - data/prepared/train.csv
    outs:
    - model/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - model/model.pkl
    - data/prepared/test.csv
    metrics:
    - metrics.json
  inference:
    cmd: python src/inference.py
    deps:
    - src/inference.py
    - model/model.pkl
    - data/unseen_data.csv
    outs:
    - data/predictions/predictions.csv
